### ISSUE TITLE
Add monitoring for ButterCMS related stuff

### ISSUE THREAD

**Issue by dpawlowski-cksource** [cksource/tiugo-monitoring#18]
## **Why**

This is to discover that products related to the `ButterCMS` brand are not working.
Additionally, we could get rid of using StatusCake for ButterCMS.

![image](https://github.com/user-attachments/assets/ac0ecfd9-4ddc-43c3-a2fa-311b37b439b6)

## **What**

- [x] Move tests from StatusCake to Tiugo Monitoring
  - ⚠️  first, ask the ButterCMS team if the below endpoints 👇  are the best ways of testing their application
  - `https://api.buttercms.com/v2/posts/?auth_token=6e9f14b48892b00079604c24c7c64a6a987456cf`
  - `https://api.buttercms.com/v2/`
  - `https://buttercms.com`
  - `https://buttercms.com/home/`
  - `https://buttercms.com/v2/posts/?auth_token=6e9f14b48892b00079604c24c7c64a6a987456cf`
  - `https://buttercms.com/login/`
- [x] Find the rest of ButterCMS certificates that should be tested (refer to [comment](https://github.com/cksource/tiugo-monitoring/issues/18#issuecomment-2348326344))
- [x] Add alerts to Grafana Cloud - https://github.com/cksource/tiugo-monitoring/issues/17

**Comment by bczerwonka-cksource** [comment]
> Move tests from StatusCake to Tiugo Monitoring

It will be good to ask the ButterCMS team about the best approach to test their application. Not sure that those endpoints are the best. To confirm.

**Comment by dpawlowski-cksource** [comment]
<img width="1069" alt="image" src="https://github.com/user-attachments/assets/b6f19afe-2902-423a-b10b-8e9e2491380c">

**Comment by LukaszGudel** [comment]
So far we are testing:
```
'https://buttercms.com',
'https://api.buttercms.com',
```

I will add 
```
staging.buttercms.com
www.buttercms.com
```

Can we get their DNS configuration? That would help with finding other certificates. Also, Bartek mentioned on Slack that their CloudFront is using an imported cert. Can I get more details about their Cloudfront? What is the domain/s that it is handling and potentially also if cloudfront origins are also using their domains?

**Comment by LukaszGudel** [comment]
All subtasks from this issue are done. Currently monitored certs for buttercms:
<img width="752" alt="image" src="https://github.com/user-attachments/assets/48125af6-eb13-4e11-a884-c0bb04544931">
