### ISSUE TITLE
Configure escalation chains and points of contact for Tiugo Monitoring alerts

### ISSUE THREAD

**Issue by LukaszGudel** [cksource/tiugo-monitoring#38]
## **Why**

We have some alerts from Tiugo Monitoring but we could use Grafana to separate the alert target and notify different teams/people depending on the failed checks. This is a followup of #17.

## **What**

- [x] Contact with Mike, Przemek, Butter, Tiny etc and create a plan for alerts redirecting -> https://www.notion.so/Alerting-flow-dda84ab3fa08412f979eaa0e5b2c0fc4
- [x] Create default Slack channels per organization
- [x] Configure Grafana integration for redirecting alerts to appropriate Slack channels
- [x] Add default escalation to On-Call team

## **When (optional)**

> _The information when it should be done - thanks to this it is easier to verify how important the task is. For example, if the issue should be done ASAP, it should be explained why ASAP._

**Comment by dpawlowski-cksource** [comment]
✅  Done

![Image](https://github.com/user-attachments/assets/685b5aa1-662d-428d-91e4-3de0dcbb3cb8)
