### ISSUE TITLE
Add tests for all public products (Phase 5)

### ISSUE THREAD

**Issue by dpawlowski-cksource** [cksource/tiugo-monitoring#5]
- [ ] Collect information about all products we are currently monit ( + technologies required for running tests for those products)
- [ ] Adjust the test runner to handle all types of tests
- [ ] Add new tests and alerts

---

Product list:
- cdn.ckeditor.com
- ckeditor.com - e2e tests?

**Comment by LukaszGudel** [comment]
Done as part of #17.
